    
    drop table ADM_GRANTABLE_ROLES if exists cascade;

    drop table ADM_PRIVILEGES if exists cascade;

    drop table ADM_ROLES if exists cascade;

    drop table ADM_ROLE_PRIVILEGES if exists cascade;

    drop table ADM_SCOPES if exists cascade;

    drop table ADM_SCOPE_MANAGERS if exists cascade;

    drop table ADM_USERS if exists cascade;

    drop table ADM_USER_ROLES if exists cascade;

    create table ADM_GRANTABLE_ROLES (
        USR_ID bigint not null,
        ROL_ID bigint not null,
        primary key (USR_ID, ROL_ID)
    );
   
    create table ADM_PRIVILEGES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        DESCRIPTION varchar(255),
        NAME varchar(255) not null,
        VALID bit not null,
        SCP_ID bigint not null,
        primary key (ID)
    );

    create table ADM_ROLES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        DESCRIPTION varchar(255),
        FROZEN bit not null,
        NAME varchar(255) not null,
        VALID bit not null,
        SCP_ID bigint not null,
        primary key (ID)
    );

    create table ADM_ROLE_PRIVILEGES (
        ROL_ID bigint not null,
        PRV_ID bigint not null,
        primary key (ROL_ID, PRV_ID)
    );

    create table ADM_SCOPES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        DESCRIPTION varchar(255),
        NAME varchar(255) not null,
        primary key (ID),
        unique (NAME)
    );

    create table ADM_SCOPE_MANAGERS (
        USR_ID bigint not null,
        SCP_ID bigint not null,
        primary key (USR_ID, SCP_ID)
    );

    create table ADM_USERS (
    	USERNAME varchar(4000),
    	PASSWORD varchar(100),
        ACTIVE char(1) not null,
        ACTIVE_FROM timestamp,
        ACTIVE_UNTIL timestamp,
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        BLOCKED char(1) not null,
        COMMENTS varchar(255),
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        LAST_LOGIN_DATE timestamp,        
        id bigint not null,
        primary key (id)
    );

    create table ADM_USER_ROLES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        ACTIVE char(1) not null,
        ACTIVE_FROM timestamp not null,
        ACTIVE_UNTIL timestamp,
        ROL_ID bigint not null,
        USR_ID bigint not null,
        primary key (ID)
    );
    
    