	
	drop table DESTINATIONS if exists cascade;

    drop table DESTINATION_LOCATIONS if exists cascade;

    drop table MAVEN_ARTIFACTS if exists cascade;

    drop table MAVEN_ARTIFACT_DESTINATIONS if exists cascade;

    drop table MAVEN_MODULES if exists cascade;

    drop table RELEASES if exists cascade;

    drop table RELEASE_HISTORY if exists cascade;

    drop table RELEASE_STEP_EXECUTIONS if exists cascade;

    drop table REPOSITORIES if exists cascade;
    
    create table DESTINATIONS (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        DEPLOYER_ID varchar(256) not null,
        ENVIRONMENT_NAME varchar(256) not null,
        HOST_NAME varchar(250) not null,
        PASSWORD varchar(256),
        PORT integer not null,
        PROTOCOL varchar(255),
        USER_NAME varchar(256),
        primary key (ID),
        unique (ID)
    );

    create table DESTINATION_LOCATIONS (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        PATH varchar(256) not null,
        LOCATION_TYPE varchar(255) not null,
        DESTINATION_ID bigint not null,
        primary key (ID),
        unique (ID)
    );

    create table MAVEN_ARTIFACTS (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        MAVEN_ARTIFACT_ID varchar(200) not null,
        MAVEN_GROUP varchar(200) not null,
        MAVEN_VERSION varchar(100) not null,
        MAVEN_MODULE_ID bigint not null,
        RELEASE_ID bigint not null,
        primary key (ID),
        unique (MAVEN_ARTIFACT_ID),
        unique (ID)
    );

    create table MAVEN_ARTIFACT_DESTINATIONS (
        MAVEN_ARTIFACTS_MAVEN_ARTIFACT_ID varchar(200) not null,
        destinations_ID bigint not null
    );

    create table MAVEN_MODULES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        NAME varchar(200) not null,
        ARTIFACT_TYPE varchar(255) not null,
        primary key (ID),
        unique (NAME),
        unique (ID)
    );

    create table RELEASES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        NAME varchar(200) not null,
        RELEASE_DATE timestamp not null,
        primary key (ID),
        unique (NAME),
        unique (ID)
    );

    create table RELEASE_HISTORY (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        RELEASE_DATE timestamp not null,
        DEPLOY_STATUS varchar(255) not null,
        RELEASE_ID bigint not null,
        primary key (ID),
        unique (ID)
    );

    create table RELEASE_STEP_EXECUTIONS (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ERROR_MESSAGE varchar(256),
        EXEUCTION_DATE timestamp not null,
        NAME varchar(200) not null,
        DEPLOY_STATUS varchar(255) not null,
        RELEASE_HISTORY_ID bigint not null,
        primary key (ID),
        unique (ID)
    );

    create table REPOSITORIES (
        ID bigint generated by default as identity (start with 1),
        CREATED timestamp,
        CREATED_BY varchar(255),
        ALTERED timestamp,
        ALTERED_BY varchar(255),
        ENABLED bit not null,
        NAME varchar(100) not null,
        REPOSITORY_URL varchar(255) not null,
        primary key (ID),
        unique (ID)
    );

    create index HOST_NAME_IDX on DESTINATIONS (HOST_NAME);

    create index LOCATION_TYPE_IDX on DESTINATION_LOCATIONS (LOCATION_TYPE);

    alter table DESTINATION_LOCATIONS 
        add constraint FK_DESTINATION_LOCATIONS_DESTINATIONS 
        foreign key (DESTINATION_ID) 
        references DESTINATIONS;

    alter table MAVEN_ARTIFACTS 
        add constraint FK_ARTIFACT_RELEASE 
        foreign key (RELEASE_ID) 
        references RELEASES;

    alter table MAVEN_ARTIFACTS 
        add constraint FK_ARTIFACT_PARENT 
        foreign key (MAVEN_MODULE_ID) 
        references MAVEN_MODULES;

    alter table MAVEN_ARTIFACT_DESTINATIONS 
        add constraint FK_DESTINATION_ARTIFACTS 
        foreign key (destinations_ID) 
        references DESTINATIONS;

    alter table RELEASE_HISTORY 
        add constraint FK_RELEAS_HISTORY_RELEASE 
        foreign key (RELEASE_ID) 
        references RELEASES;

    alter table RELEASE_STEP_EXECUTIONS 
        add constraint FK_STEP_EXECUTION_RELEASE_HISTORY 
        foreign key (RELEASE_HISTORY_ID) 
        references RELEASE_HISTORY;
