DELETE FROM SEC.ADM_ROLE_PRIVILEGES;
DELETE FROM SEC.ADM_PRIVILEGES;
DELETE FROM SEC.ADM_PRIVILEGES;
DELETE FROM SEC.ADM_USER_ROLES;
DELETE FROM SEC.ADM_ROLES;
DELETE FROM SEC.ADM_SCOPES;
DELETE FROM SEC.ADM_USERS;
