CREATE OR REPLACE FUNCTION f_revoke_all_from_role(_role text)
	RETURNS void AS
$BODY$
BEGIN

	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = _role) THEN
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DESTINATIONS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DESTINATION_HOSTS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DEPLOYER_PARAMETERS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.ENVIRONMENTS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_ARTIFACTS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_ARTIFACT_SNAPSHOTS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_MODULES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_MODULE_DESTINATIONS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASE_EXECUTIONS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASE_EXECUTION_LOGS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASE_STEP_EXECUTIONS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.REPOSITORIES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.ENVIRONMENT_NOTIFICATION_SETTINGS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DEPLOYERS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DEPLOYER_PARAMETER_TEMPLATES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DEPLOYMENT_DEPENDENCIES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.ENVIRONMENT_DEPLOYERS FROM ' || quote_ident(_role);
		
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_USER_GROUPS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_USER_GROUP_USERS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_USERS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_GRANTABLE_ROLES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_PRIVILEGES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_ROLE_PRIVILEGES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_ROLES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_SCOPE_MANAGERS FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_SCOPES FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ADM_USER_ROLES FROM ' || quote_ident(_role);
		
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DESTINATIONS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DESTINATION_HOSTS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.DEPLOYER_PARAMETERS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.ENVIRONMENTS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_ARTIFACTS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_ARTIFACT_SNAPSHOTS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.MAVEN_MODULES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASE_EXECUTIONS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.REL_EXEC_LOGS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.RELEASE_STEP_EXECUTIONS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.REPOSITORIES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON ADM.ENVIRONMENT_NOTIFICATION_SETTINGS_SEQ FROM ' || quote_ident(_role);
		
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.PRIVILEGES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.ROLES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.SCOPES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.USER_GROUPS_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.USER_ROLES_SEQ FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE ALL PRIVILEGES ON SEC.USERS_SEQ FROM ' || quote_ident(_role);	
		
		EXECUTE 'REVOKE USAGE ON SCHEMA ADM FROM ' || quote_ident(_role);
		EXECUTE 'REVOKE USAGE ON SCHEMA SEC FROM ' || quote_ident(_role);
	END IF;

END;
$BODY$ LANGUAGE plpgsql;
