INSERT INTO ADM_USERS (ID, USERNAME, PASSWORD, ACTIVE, BLOCKED, CREATED, CREATED_BY)
VALUES (-1, 's-petrus', 'c514ff8f08ef1693cd082d5362b13422dc643ecf', 'Y', 'N', current_timestamp, 's-petrus');

INSERT INTO ADM_SCOPES (ID, NAME, CREATED, CREATED_BY) VALUES
 (-1, 'ADM Security unit test', current_timestamp, 's-petrus');

INSERT INTO ADM_ROLES (ID, SCP_ID, NAME, FROZEN, VALID, CREATED, CREATED_BY)
 VALUES (-1, (SELECT ID FROM ADM_SCOPES WHERE NAME = 'ADM Security unit test'), 'API Test role', 'Y', 'Y', current_timestamp, 's-petrus');

INSERT INTO ADM_PRIVILEGES (ID, SCP_ID, NAME, VALID, CREATED, CREATED_BY)
 VALUES (-1, (SELECT ID FROM ADM_SCOPES WHERE NAME = 'ADM Security unit test'), 'API Delete', 'Y', current_timestamp, 's-petrus');
INSERT INTO ADM_PRIVILEGES (ID, SCP_ID, NAME, VALID, CREATED, CREATED_BY)
 VALUES (-2, (SELECT ID FROM ADM_SCOPES WHERE NAME = 'ADM Security unit test'), 'API Insert', 'N', current_timestamp, 's-petrus');

INSERT INTO ADM_ROLE_PRIVILEGES (ROL_ID, PRV_ID)
 VALUES ((SELECT ID FROM ROLES WHERE NAME = 'API Test role'), (SELECT ID FROM ADM_PRIVILEGES WHERE NAME = 'API Delete'));
INSERT INTO ADM_ROLE_PRIVILEGES (ROL_ID, PRV_ID)
 VALUES ((SELECT ID FROM ROLES WHERE NAME = 'API Test role'), (SELECT ID FROM ADM_PRIVILEGES WHERE NAME = 'API Insert')); 

 INSERT INTO ADM_USER_ROLES (ID, USR_ID, ROL_ID, ACTIVE, ACTIVE_FROM, CREATED, CREATED_BY)
 VALUES (-1, (SELECT ID FROM ADM_USERS WHERE ID = (SELECT ID FROM USERS WHERE USERNAME = 's-petrus')), (SELECT ID FROM ADM_ROLES WHERE NAME = 'API Test role'), 'Y', current_timestamp, current_timestamp, 's-petrus');
 