GRANT SELECT, INSERT, UPDATE ON ADM.DESTINATIONS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.DESTINATION_HOSTS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.DEPLOYER_PARAMETERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.ENVIRONMENTS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.MAVEN_ARTIFACTS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.MAVEN_ARTIFACT_SNAPSHOTS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.MAVEN_MODULES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.MAVEN_MODULE_DESTINATIONS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.RELEASES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.RELEASE_EXECUTIONS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.RELEASE_EXECUTION_LOGS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.RELEASE_STEP_EXECUTIONS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.REPOSITORIES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.ENVIRONMENT_DEPLOYERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.ENVIRONMENT_NOTIFICATION_SETTINGS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.DEPLOYERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE ON ADM.DEPLOYER_PARAMETER_TEMPLATES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADM.DEPLOYMENT_DEPENDENCIES TO deployment_manager_demo;

GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_USER_GROUPS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_USER_GROUP_USERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_USERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_GRANTABLE_ROLES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_PRIVILEGES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_ROLE_PRIVILEGES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_ROLES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_SCOPE_MANAGERS TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_SCOPES TO deployment_manager_demo;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEC.ADM_USER_ROLES TO deployment_manager_demo;

GRANT SELECT, UPDATE ON ADM.DESTINATIONS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.DESTINATION_HOSTS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.DEPLOYER_PARAMETERS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.ENVIRONMENTS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.MAVEN_ARTIFACTS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.MAVEN_ARTIFACT_SNAPSHOTS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.MAVEN_MODULES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.RELEASES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.RELEASE_EXECUTIONS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.REL_EXEC_LOGS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.RELEASE_STEP_EXECUTIONS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.REPOSITORIES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON ADM.ENVIRONMENT_NOTIFICATION_SETTINGS_SEQ TO deployment_manager_demo;

GRANT SELECT, UPDATE ON SEC.PRIVILEGES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON SEC.ROLES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON SEC.SCOPES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON SEC.USER_GROUPS_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON SEC.USER_ROLES_SEQ TO deployment_manager_demo;
GRANT SELECT, UPDATE ON SEC.USERS_SEQ TO deployment_manager_demo;

GRANT deployment_manager_demo TO adm_gui_demo;

GRANT USAGE ON SCHEMA ADM TO deployment_manager_demo;
GRANT USAGE ON SCHEMA SEC TO deployment_manager_demo;
